package Client_Java;


import java.awt.Color;
import javax.swing.table.DefaultTableCellRenderer;
public class LongestWordUI extends javax.swing.JFrame {

   
    public LongestWordUI() {
        getComponents();
        firstPlace.setBackground(new Color(0,0,0,1));
        secondPlace.setBackground(new Color(0,0,0,1));
        thirdPlace.setBackground(new Color(0,0,0,1));
        jTable2.setBackground(new Color(0,0,0,0));

        ((DefaultTableCellRenderer)jTable2.getDefaultRenderer(Object.class)).setBackground(new Color(0,0,0,0));

        jTable2.setGridColor(Color.WHITE);

        jTable2.setForeground(Color.WHITE);

        jScrollPane3.setBackground(new Color(0,0,0,0));

        jScrollPane3.setOpaque(false);
        jTable2.setOpaque(false);
        ((DefaultTableCellRenderer)jTable2.getDefaultRenderer(Object.class)).setOpaque(false);
        jScrollPane3.getViewport().setOpaque(false);

        jTable2.setShowGrid(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    

    private void firstPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstPlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstPlaceActionPerformed

    
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LongestWordUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField firstPlace;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField secondPlace;
    private javax.swing.JTextField thirdPlace;
    // End of variables declaration//GEN-END:variables
}
