package Client_Java.corbaGame;

/**
* corbaGame/checkLoginHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Thursday, 25 May 2023 1:47:15 PM SGT
*/

public final class checkLoginHolder implements org.omg.CORBA.portable.Streamable
{
  public checkLogin value = null;

  public checkLoginHolder ()
  {
  }

  public checkLoginHolder (checkLogin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = checkLoginHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    checkLoginHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return checkLoginHelper.type ();
  }

}
