package Client_Java.corbaGame;

/**
* corbaGame/getRoundWinHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Thursday, 25 May 2023 1:47:15 PM SGT
*/

public final class getRoundWinHolder implements org.omg.CORBA.portable.Streamable
{
  public getRoundWin value = null;

  public getRoundWinHolder ()
  {
  }

  public getRoundWinHolder (getRoundWin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = getRoundWinHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    getRoundWinHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return getRoundWinHelper.type ();
  }

}
