package Client_Java.corbaGame;

/**
* corbaGame/invalidHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Thursday, 25 May 2023 1:47:15 PM SGT
*/

public final class invalidHolder implements org.omg.CORBA.portable.Streamable
{
  public invalid value = null;

  public invalidHolder ()
  {
  }

  public invalidHolder (invalid initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = invalidHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    invalidHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return invalidHelper.type ();
  }

}
