package Client_Java.corbaGame;


/**
* corbaGame/InvalidWord.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Friday, 26 May 2023 11:05:21 PM SGT
*/

public final class InvalidWord extends org.omg.CORBA.UserException
{
  public String message = null;

  public InvalidWord ()
  {
    super(InvalidWordHelper.id());
  } // ctor

  public InvalidWord (String _message)
  {
    super(InvalidWordHelper.id());
    message = _message;
  } // ctor


  public InvalidWord (String $reason, String _message)
  {
    super(InvalidWordHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class InvalidWord
