package Client_Java.corbaGame;


/**
* corbaGame/wordy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Friday, 26 May 2023 11:05:21 PM SGT
*/

public interface wordy extends wordyOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface wordy
