package Client_Java.CORBA_IDL;


/**
* CORBA_IDL/wordyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA_IDL.idl
* Thursday, 27 April 2023 11:23:02 PM SGT
*/

public interface wordyOperations 
{
  void login (String username, String password);
} // interface wordyOperations
