package Server_Java.corba;

/**
* corba/checkLoginHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Wednesday, 24 May 2023 9:37:24 AM SGT
*/

public final class checkLoginHolder implements org.omg.CORBA.portable.Streamable
{
  public checkLogin value = null;

  public checkLoginHolder ()
  {
  }

  public checkLoginHolder (checkLogin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = checkLoginHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    checkLoginHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return checkLoginHelper.type ();
  }

}
