package Server_Java.corba;

/**
* corba/GameExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Thursday, May 11, 2023 8:55:27 AM CST
*/

public final class GameExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public GameException value = null;

  public GameExceptionHolder ()
  {
  }

  public GameExceptionHolder (GameException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameExceptionHelper.type ();
  }

}
