package Server_Java.corba;


/**
* corba/GameException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Monday, May 15, 2023 8:32:03 AM CST
*/

public final class GameException extends org.omg.CORBA.UserException
{
  public String message = null;

  public GameException ()
  {
    super(GameExceptionHelper.id());
  } // ctor

  public GameException (String _message)
  {
    super(GameExceptionHelper.id());
    message = _message;
  } // ctor


  public GameException (String $reason, String _message)
  {
    super(GameExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class GameException
