package Server_Java.corba;


/**
* corba/getRoundWin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Wednesday, 24 May 2023 9:37:24 AM SGT
*/

public final class getRoundWin extends org.omg.CORBA.UserException
{
  public String message = null;

  public getRoundWin ()
  {
    super(getRoundWinHelper.id());
  } // ctor

  public getRoundWin (String _message)
  {
    super(getRoundWinHelper.id());
    message = _message;
  } // ctor


  public getRoundWin (String $reason, String _message)
  {
    super(getRoundWinHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class getRoundWin
