package Server_Java.corba;


/**
* corba/getWin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Wednesday, 24 May 2023 9:37:24 AM SGT
*/

public final class getWin extends org.omg.CORBA.UserException
{
  public String message = null;

  public getWin ()
  {
    super(getWinHelper.id());
  } // ctor

  public getWin (String _message)
  {
    super(getWinHelper.id());
    message = _message;
  } // ctor


  public getWin (String $reason, String _message)
  {
    super(getWinHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class getWin
