package Server_Java.corba;


/**
* corba/isSameLength.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Wednesday, 24 May 2023 9:37:24 AM SGT
*/

public final class isSameLength extends org.omg.CORBA.UserException
{
  public String message = null;

  public isSameLength ()
  {
    super(isSameLengthHelper.id());
  } // ctor

  public isSameLength (String _message)
  {
    super(isSameLengthHelper.id());
    message = _message;
  } // ctor


  public isSameLength (String $reason, String _message)
  {
    super(isSameLengthHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class isSameLength
