package Server_Java.corba;


/**
* corba/lobbyPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Monday, May 15, 2023 8:32:03 AM CST
*/

public abstract class lobbyPOA extends org.omg.PortableServer.Servant
 implements lobbyOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("time", new java.lang.Integer (0));
    _methods.put ("playerList", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // corba/lobby/time
       {
         double countdown = in.read_double ();
         this.time (countdown);
         out = $rh.createReply();
         break;
       }

       case 1:  // corba/lobby/playerList
       {
         String message = in.read_string ();
         this.playerList (message);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corba/lobby:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public lobby _this() 
  {
    return lobbyHelper.narrow(
    super._this_object());
  }

  public lobby _this(org.omg.CORBA.ORB orb) 
  {
    return lobbyHelper.narrow(
    super._this_object(orb));
  }


} // class lobbyPOA
