package Server_Java.corba;

/**
* corba/lobbyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Monday, May 15, 2023 8:32:03 AM CST
*/

public final class lobbyHolder implements org.omg.CORBA.portable.Streamable
{
  public lobby value = null;

  public lobbyHolder ()
  {
  }

  public lobbyHolder (lobby initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = lobbyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    lobbyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return lobbyHelper.type ();
  }

}
