package Server_Java.corba;


/**
* corba/lobbyHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Monday, May 15, 2023 8:32:03 AM CST
*/

abstract public class lobbyHelper
{
  private static String  _id = "IDL:corba/lobby:1.0";

  public static void insert (org.omg.CORBA.Any a, lobby that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static lobby extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (lobbyHelper.id (), "lobby");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static lobby read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_lobbyStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, lobby value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static lobby narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof lobby)
      return (lobby)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _lobbyStub stub = new _lobbyStub();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static lobby unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof lobby)
      return (lobby)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _lobbyStub stub = new _lobbyStub();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
