package Server_Java.corba;


/**
* corba/notEnoughPlayers.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Wednesday, 24 May 2023 9:37:24 AM SGT
*/

public final class notEnoughPlayers extends org.omg.CORBA.UserException
{
  public String message = null;

  public notEnoughPlayers ()
  {
    super(notEnoughPlayersHelper.id());
  } // ctor

  public notEnoughPlayers (String _message)
  {
    super(notEnoughPlayersHelper.id());
    message = _message;
  } // ctor


  public notEnoughPlayers (String $reason, String _message)
  {
    super(notEnoughPlayersHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class notEnoughPlayers
