package Server_Java.corba;


import java.util.Arrays;

/**
* corba/PlayersHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Monday, 8 May 2023 10:12:23 PM SGT
*/

public final class PlayersHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public PlayersHolder ()
  {
  }

  public PlayersHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PlayersHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PlayersHelper.write (o, Arrays.asList(value));
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PlayersHelper.type ();
  }

}
