package Server_Java.corba;


/**
* corba/sendLobby.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Monday, May 15, 2023 8:32:03 AM CST
*/

public interface sendLobby extends sendLobbyOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface sendLobby
