package Server_Java.corba;


/**
* corba/sendLobbyPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Monday, May 15, 2023 8:32:03 AM CST
*/

public abstract class sendLobbyPOA extends org.omg.PortableServer.Servant
 implements sendLobbyOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sendTimer", new java.lang.Integer (0));
    _methods.put ("sendPlayerList", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // corba/sendLobby/sendTimer
       {
         lobby objref = lobbyHelper.read (in);
         String message = in.read_string ();
         String $result = null;
         $result = this.sendTimer (objref, message);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // corba/sendLobby/sendPlayerList
       {
         lobby objref = lobbyHelper.read (in);
         String message = in.read_string ();
         String $result = null;
         $result = this.sendPlayerList (objref, message);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corba/sendLobby:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public sendLobby _this() 
  {
    return sendLobbyHelper.narrow(
    super._this_object());
  }

  public sendLobby _this(org.omg.CORBA.ORB orb) 
  {
    return sendLobbyHelper.narrow(
    super._this_object(orb));
  }


} // class sendLobbyPOA
