package Server_Java.corba;


/**
* corba/WordyCallback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Wednesday, 24 May 2023 9:37:24 AM SGT
*/

public interface WordyCallback extends WordyCallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface WordyCallback
