package Server_Java.corba;

/**
* corba/wordyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Thursday, May 11, 2023 8:55:27 AM CST
*/

public final class wordyHolder implements org.omg.CORBA.portable.Streamable
{
  public wordy value = null;

  public wordyHolder ()
  {
  }

  public wordyHolder (wordy initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyHelper.type ();
  }

}
