package Server_Java.corba;


/**
* corba/wordyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Thursday, May 11, 2023 8:55:27 AM CST
*/

public interface wordyOperations 
{
  String login (String username, String password);
  boolean joinGame (String playerName) throws GameException;
  void playWord (String playerName, String word) throws GameException;
  boolean status (String playerName);
  String generateLetters ();
  boolean timer ();
  void leaveGame (String playerName) throws GameException;
  void receiveMessage (String receiveMessage);
} // interface wordyOperations
