package Server_Java.corba;


/**
* corba/wordyPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Tuesday, 23 May 2023 12:11:55 AM SGT
*/

public abstract class wordyPOA extends org.omg.PortableServer.Servant
 implements wordyOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("login", new java.lang.Integer (0));
    _methods.put ("exit", new java.lang.Integer (1));
    _methods.put ("joinLobby", new java.lang.Integer (2));
    _methods.put ("timerServer", new java.lang.Integer (3));
    _methods.put ("gettimer", new java.lang.Integer (4));
    _methods.put ("getGeneratedLetter", new java.lang.Integer (5));
    _methods.put ("playerInGameList", new java.lang.Integer (6));
    _methods.put ("playWord", new java.lang.Integer (7));
    _methods.put ("getValidWordFromClients", new java.lang.Integer (8));
    _methods.put ("getWinner", new java.lang.Integer (9));
    _methods.put ("generateLetters", new java.lang.Integer (10));
    _methods.put ("status", new java.lang.Integer (11));
    _methods.put ("lobbyPlayerCount", new java.lang.Integer (12));
    _methods.put ("leaveGame", new java.lang.Integer (13));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // corba/wordy/login
       {
         String username = in.read_string ();
         String password = in.read_string ();
         String $result = null;
         $result = this.login (username, password);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // corba/wordy/exit
       {
         String username = in.read_string ();
         this.exit (username);
         out = $rh.createReply();
         break;
       }

       case 2:  // corba/wordy/joinLobby
       {
         try {
           String playerName = in.read_string ();
           boolean $result = false;
           $result = this.joinLobby (playerName);
           out = $rh.createReply();
           out.write_boolean ($result);
         } catch (GameException $ex) {
           out = $rh.createExceptionReply ();
           GameExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // corba/wordy/timerServer
       {
         this.timerServer ();
         out = $rh.createReply();
         break;
       }

       case 4:  // corba/wordy/gettimer
       {
         double $result = (double)0;
         $result = this.gettimer ();
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 5:  // corba/wordy/getGeneratedLetter
       {
         String $result = null;
         $result = this.getGeneratedLetter ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // corba/wordy/playerInGameList
       {
         String $result = null;
         $result = this.playerInGameList ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // corba/wordy/playWord
       {
         try {
           String playerName = in.read_string ();
           String word = in.read_string ();
           this.playWord (playerName, word);
           out = $rh.createReply();
         } catch (InvalidWord $ex) {
           out = $rh.createExceptionReply ();
           InvalidWordHelper.write (out, $ex);
         }
         break;
       }

       case 8:  // corba/wordy/getValidWordFromClients
       {
         String $result = null;
         $result = this.getValidWordFromClients ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 9:  // corba/wordy/getWinner
       {
         String $result = null;
         $result = this.getWinner ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 10:  // corba/wordy/generateLetters
       {
         this.generateLetters ();
         out = $rh.createReply();
         break;
       }

       case 11:  // corba/wordy/status
       {
         String playerName = in.read_string ();
         boolean $result = false;
         $result = this.status (playerName);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 12:  // corba/wordy/lobbyPlayerCount
       {
         double $result = (double)0;
         $result = this.lobbyPlayerCount ();
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 13:  // corba/wordy/leaveGame
       {
         try {
           String playerName = in.read_string ();
           this.leaveGame (playerName);
           out = $rh.createReply();
         } catch (GameException $ex) {
           out = $rh.createExceptionReply ();
           GameExceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corba/wordy:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public wordy _this() 
  {
    return wordyHelper.narrow(
    super._this_object());
  }

  public wordy _this(org.omg.CORBA.ORB orb) 
  {
    return wordyHelper.narrow(
    super._this_object(orb));
  }


} // class wordyPOA
