package Server_Java.corba;


import java.util.List;

/**
* corba/WordyCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Monday, 8 May 2023 10:12:23 PM SGT
*/

public interface WordyCallbackOperations 
{
  void notifyCountdownStarted (int count);
  void notifyPlayersList (List<String> players);
  void notifyGameStarted ();
} // interface WordyCallbackOperations
