package Server_Java.corba;


/**
* corba/WordyCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Monday, May 15, 2023 8:32:03 AM CST
*/

public interface WordyCallbackOperations 
{
  void notifyCountdownStarted (int count);
  void notifyPlayersList (String[] players);
  void notifyGameStarted ();
} // interface WordyCallbackOperations
