package Server_Java.corba;


/**
* corba/WordyCallback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Monday, 8 May 2023 10:12:23 PM SGT
*/

public interface WordyCallback extends WordyCallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface WordyCallback
