package Server_Java.corba;


/**
* corba/wordyPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Thursday, May 11, 2023 8:55:27 AM CST
*/

public abstract class wordyPOA extends org.omg.PortableServer.Servant
 implements wordyOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("login", new java.lang.Integer (0));
    _methods.put ("joinGame", new java.lang.Integer (1));
    _methods.put ("playWord", new java.lang.Integer (2));
    _methods.put ("status", new java.lang.Integer (3));
    _methods.put ("generateLetters", new java.lang.Integer (4));
    _methods.put ("timer", new java.lang.Integer (5));
    _methods.put ("leaveGame", new java.lang.Integer (6));
    _methods.put ("receiveMessage", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // corba/wordy/login
       {
         String username = in.read_string ();
         String password = in.read_string ();
         String $result = null;
         $result = this.login (username, password);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // corba/wordy/joinGame
       {
         try {
           String playerName = in.read_string ();
           boolean $result = false;
           $result = this.joinGame (playerName);
           out = $rh.createReply();
           out.write_boolean ($result);
         } catch (GameException $ex) {
           out = $rh.createExceptionReply ();
           GameExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // corba/wordy/playWord
       {
         try {
           String playerName = in.read_string ();
           String word = in.read_string ();
           this.playWord (playerName, word);
           out = $rh.createReply();
         } catch (GameException $ex) {
           out = $rh.createExceptionReply ();
           GameExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // corba/wordy/status
       {
         String playerName = in.read_string ();
         boolean $result = false;
         $result = this.status (playerName);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // corba/wordy/generateLetters
       {
         String $result = null;
         $result = this.generateLetters ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // corba/wordy/timer
       {
         boolean $result = false;
         $result = this.timer ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 6:  // corba/wordy/leaveGame
       {
         try {
           String playerName = in.read_string ();
           this.leaveGame (playerName);
           out = $rh.createReply();
         } catch (GameException $ex) {
           out = $rh.createExceptionReply ();
           GameExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 7:  // corba/wordy/receiveMessage
       {
         String receiveMessage = in.read_string ();
         this.receiveMessage (receiveMessage);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corba/wordy:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public wordy _this() 
  {
    return wordyHelper.narrow(
    super._this_object());
  }

  public wordy _this(org.omg.CORBA.ORB orb) 
  {
    return wordyHelper.narrow(
    super._this_object(orb));
  }


} // class wordyPOA
