package Server_Java.corba;


/**
* corba/wordyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Thursday, 4 May 2023 7:08:40 PM SGT
*/

public interface wordyOperations 
{
  String login (String username, String password);
  boolean joinGame (String playerName) throws GameException;
  void playWord (String playerName, String word) throws GameException;
} // interface wordyOperations
