package Server_Java.corba;


/**
* corba/wordy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Sunday, 14 May 2023 9:41:27 PM SGT
*/

public interface wordy extends wordyOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface wordy
