package Server_Java.corba;


import java.util.Arrays;
import java.util.List;

/**
* corba/WordyCallbackPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Monday, 8 May 2023 10:12:23 PM SGT
*/

public abstract class WordyCallbackPOA extends org.omg.PortableServer.Servant
 implements WordyCallbackOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("notifyCountdownStarted", new java.lang.Integer (0));
    _methods.put ("notifyPlayersList", new java.lang.Integer (1));
    _methods.put ("notifyGameStarted", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // corba/WordyCallback/notifyCountdownStarted
       {
         int count = in.read_long ();
         this.notifyCountdownStarted (count);
         out = $rh.createReply();
         break;
       }

       case 1:  // corba/WordyCallback/notifyPlayersList
       {
         String[] players = PlayersHelper.read (in);
         this.notifyPlayersList (Arrays.asList(players));
         out = $rh.createReply();
         break;
       }

       case 2:  // corba/WordyCallback/notifyGameStarted
       {
         this.notifyGameStarted ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corba/WordyCallback:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public WordyCallback _this() 
  {
    return WordyCallbackHelper.narrow(
    super._this_object());
  }

  public WordyCallback _this(org.omg.CORBA.ORB orb) 
  {
    return WordyCallbackHelper.narrow(
    super._this_object(orb));
  }


  public abstract void notifyPlayersList(List<String> players);
} // class WordyCallbackPOA
