package Server_Java.corba;


/**
* corba/WordyCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Thursday, May 11, 2023 8:55:27 AM CST
*/

public interface WordyCallbackOperations 
{
  void notifyCountdownStarted (int count);
  void notifyPlayersList (String[] players);
  void notifyGameStarted ();
  void sendMessage (String sendMessage);
} // interface WordyCallbackOperations
