package corbaGame;

/**
* corbaGame/checkLoginHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Thursday, 17 July 2025 1:31:24 PM SGT
*/

public final class checkLoginHolder implements org.omg.CORBA.portable.Streamable
{
  public corbaGame.checkLogin value = null;

  public checkLoginHolder ()
  {
  }

  public checkLoginHolder (corbaGame.checkLogin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbaGame.checkLoginHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbaGame.checkLoginHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbaGame.checkLoginHelper.type ();
  }

}
