package corbaGame;

/**
* corbaGame/GameExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Thursday, 17 July 2025 1:31:24 PM SGT
*/

public final class GameExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public corbaGame.GameException value = null;

  public GameExceptionHolder ()
  {
  }

  public GameExceptionHolder (corbaGame.GameException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbaGame.GameExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbaGame.GameExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbaGame.GameExceptionHelper.type ();
  }

}
