package corbaGame;

/**
* corbaGame/getRoundWinHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Thursday, 17 July 2025 1:31:24 PM SGT
*/

public final class getRoundWinHolder implements org.omg.CORBA.portable.Streamable
{
  public corbaGame.getRoundWin value = null;

  public getRoundWinHolder ()
  {
  }

  public getRoundWinHolder (corbaGame.getRoundWin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbaGame.getRoundWinHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbaGame.getRoundWinHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbaGame.getRoundWinHelper.type ();
  }

}
