package corbaGame;


/**
* corbaGame/getTopHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Thursday, 17 July 2025 1:31:24 PM SGT
*/

public final class getTopHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public getTopHolder ()
  {
  }

  public getTopHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbaGame.getTopHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbaGame.getTopHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbaGame.getTopHelper.type ();
  }

}
