package corbaGame;


/**
* corbaGame/getWinsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Thursday, 17 July 2025 1:31:25 PM SGT
*/

public final class getWinsHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public getWinsHolder ()
  {
  }

  public getWinsHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbaGame.getWinsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbaGame.getWinsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbaGame.getWinsHelper.type ();
  }

}
