package corbaGame;

/**
* corbaGame/getWinHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Thursday, 17 July 2025 1:31:24 PM SGT
*/

public final class getWinHolder implements org.omg.CORBA.portable.Streamable
{
  public corbaGame.getWin value = null;

  public getWinHolder ()
  {
  }

  public getWinHolder (corbaGame.getWin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbaGame.getWinHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbaGame.getWinHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbaGame.getWinHelper.type ();
  }

}
