package corbaGame;

/**
* corbaGame/invalidHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Thursday, 17 July 2025 1:31:24 PM SGT
*/

public final class invalidHolder implements org.omg.CORBA.portable.Streamable
{
  public corbaGame.invalid value = null;

  public invalidHolder ()
  {
  }

  public invalidHolder (corbaGame.invalid initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbaGame.invalidHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbaGame.invalidHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbaGame.invalidHelper.type ();
  }

}
