package corbaGame;


/**
* corbaGame/isSameLength.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Thursday, 17 July 2025 1:31:24 PM SGT
*/

public final class isSameLength extends org.omg.CORBA.UserException
{
  public String message = null;

  public isSameLength ()
  {
    super(isSameLengthHelper.id());
  } // ctor

  public isSameLength (String _message)
  {
    super(isSameLengthHelper.id());
    message = _message;
  } // ctor


  public isSameLength (String $reason, String _message)
  {
    super(isSameLengthHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class isSameLength
