package corbaGame;

/**
* corbaGame/isSameLengthHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Thursday, 17 July 2025 1:31:24 PM SGT
*/

public final class isSameLengthHolder implements org.omg.CORBA.portable.Streamable
{
  public corbaGame.isSameLength value = null;

  public isSameLengthHolder ()
  {
  }

  public isSameLengthHolder (corbaGame.isSameLength initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbaGame.isSameLengthHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbaGame.isSameLengthHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbaGame.isSameLengthHelper.type ();
  }

}
