package corbaGame;

/**
* corbaGame/notEnoughPlayersHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Thursday, 17 July 2025 1:31:24 PM SGT
*/

public final class notEnoughPlayersHolder implements org.omg.CORBA.portable.Streamable
{
  public corbaGame.notEnoughPlayers value = null;

  public notEnoughPlayersHolder ()
  {
  }

  public notEnoughPlayersHolder (corbaGame.notEnoughPlayers initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbaGame.notEnoughPlayersHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbaGame.notEnoughPlayersHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbaGame.notEnoughPlayersHelper.type ();
  }

}
