package corbaGame;

/**
* corbaGame/notFoundHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Thursday, 17 July 2025 1:31:24 PM SGT
*/

public final class notFoundHolder implements org.omg.CORBA.portable.Streamable
{
  public corbaGame.notFound value = null;

  public notFoundHolder ()
  {
  }

  public notFoundHolder (corbaGame.notFound initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbaGame.notFoundHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbaGame.notFoundHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbaGame.notFoundHelper.type ();
  }

}
