package corbaGame;


/**
* corbaGame/validatedLogin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Thursday, 17 July 2025 1:31:24 PM SGT
*/

public final class validatedLogin extends org.omg.CORBA.UserException
{
  public String message = null;

  public validatedLogin ()
  {
    super(validatedLoginHelper.id());
  } // ctor

  public validatedLogin (String _message)
  {
    super(validatedLoginHelper.id());
    message = _message;
  } // ctor


  public validatedLogin (String $reason, String _message)
  {
    super(validatedLoginHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class validatedLogin
