package corbaGame;

/**
* corbaGame/validatedLoginHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Thursday, 17 July 2025 1:31:24 PM SGT
*/

public final class validatedLoginHolder implements org.omg.CORBA.portable.Streamable
{
  public corbaGame.validatedLogin value = null;

  public validatedLoginHolder ()
  {
  }

  public validatedLoginHolder (corbaGame.validatedLogin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbaGame.validatedLoginHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbaGame.validatedLoginHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbaGame.validatedLoginHelper.type ();
  }

}
