package corbaGame;


/**
* corbaGame/wordyPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Thursday, 17 July 2025 1:31:25 PM SGT
*/

public abstract class wordyPOA extends org.omg.PortableServer.Servant
 implements corbaGame.wordyOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("login", new java.lang.Integer (0));
    _methods.put ("exit", new java.lang.Integer (1));
    _methods.put ("joinLobby", new java.lang.Integer (2));
    _methods.put ("timerServer", new java.lang.Integer (3));
    _methods.put ("gettimer", new java.lang.Integer (4));
    _methods.put ("getGeneratedLetter", new java.lang.Integer (5));
    _methods.put ("playerInGameList", new java.lang.Integer (6));
    _methods.put ("playWord", new java.lang.Integer (7));
    _methods.put ("getValidWordFromClients", new java.lang.Integer (8));
    _methods.put ("getWinner", new java.lang.Integer (9));
    _methods.put ("generateLetters", new java.lang.Integer (10));
    _methods.put ("getGameState", new java.lang.Integer (11));
    _methods.put ("getCurrentGameTime", new java.lang.Integer (12));
    _methods.put ("getLobbyCountdown", new java.lang.Integer (13));
    _methods.put ("isInLobbyCountdown", new java.lang.Integer (14));
    _methods.put ("getServerTimestamp", new java.lang.Integer (15));
    _methods.put ("isGameActive", new java.lang.Integer (16));
    _methods.put ("getGameEnded", new java.lang.Integer (17));
    _methods.put ("getWinnerName", new java.lang.Integer (18));
    _methods.put ("startNewRound", new java.lang.Integer (19));
    _methods.put ("lobbyPlayerCount", new java.lang.Integer (20));
    _methods.put ("leaveGame", new java.lang.Integer (21));
    _methods.put ("displayWordList", new java.lang.Integer (22));
    _methods.put ("displayWinsList", new java.lang.Integer (23));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // corbaGame/wordy/login
       {
         try {
           String username = in.read_string ();
           String password = in.read_string ();
           this.login (username, password);
           out = $rh.createReply();
         } catch (corbaGame.checkLogin $ex) {
           out = $rh.createExceptionReply ();
           corbaGame.checkLoginHelper.write (out, $ex);
         } catch (corbaGame.notFound $ex) {
           out = $rh.createExceptionReply ();
           corbaGame.notFoundHelper.write (out, $ex);
         } catch (corbaGame.invalid $ex) {
           out = $rh.createExceptionReply ();
           corbaGame.invalidHelper.write (out, $ex);
         } catch (corbaGame.validatedLogin $ex) {
           out = $rh.createExceptionReply ();
           corbaGame.validatedLoginHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // corbaGame/wordy/exit
       {
         String username = in.read_string ();
         this.exit (username);
         out = $rh.createReply();
         break;
       }

       case 2:  // corbaGame/wordy/joinLobby
       {
         try {
           String playerName = in.read_string ();
           boolean $result = false;
           $result = this.joinLobby (playerName);
           out = $rh.createReply();
           out.write_boolean ($result);
         } catch (corbaGame.GameException $ex) {
           out = $rh.createExceptionReply ();
           corbaGame.GameExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // corbaGame/wordy/timerServer
       {
         this.timerServer ();
         out = $rh.createReply();
         break;
       }

       case 4:  // corbaGame/wordy/gettimer
       {
         double $result = (double)0;
         $result = this.gettimer ();
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 5:  // corbaGame/wordy/getGeneratedLetter
       {
         String $result = null;
         $result = this.getGeneratedLetter ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // corbaGame/wordy/playerInGameList
       {
         String $result = null;
         $result = this.playerInGameList ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // corbaGame/wordy/playWord
       {
         try {
           String playerName = in.read_string ();
           String word = in.read_string ();
           this.playWord (playerName, word);
           out = $rh.createReply();
         } catch (corbaGame.InvalidWord $ex) {
           out = $rh.createExceptionReply ();
           corbaGame.InvalidWordHelper.write (out, $ex);
         }
         break;
       }

       case 8:  // corbaGame/wordy/getValidWordFromClients
       {
         String $result = null;
         $result = this.getValidWordFromClients ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 9:  // corbaGame/wordy/getWinner
       {
         try {
           this.getWinner ();
           out = $rh.createReply();
         } catch (corbaGame.isSameLength $ex) {
           out = $rh.createExceptionReply ();
           corbaGame.isSameLengthHelper.write (out, $ex);
         } catch (corbaGame.getWin $ex) {
           out = $rh.createExceptionReply ();
           corbaGame.getWinHelper.write (out, $ex);
         } catch (corbaGame.getRoundWin $ex) {
           out = $rh.createExceptionReply ();
           corbaGame.getRoundWinHelper.write (out, $ex);
         }
         break;
       }

       case 10:  // corbaGame/wordy/generateLetters
       {
         this.generateLetters ();
         out = $rh.createReply();
         break;
       }


  // New synchronized timer methods
       case 11:  // corbaGame/wordy/getGameState
       {
         String $result = null;
         $result = this.getGameState ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 12:  // corbaGame/wordy/getCurrentGameTime
       {
         int $result = (int)0;
         $result = this.getCurrentGameTime ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 13:  // corbaGame/wordy/getLobbyCountdown
       {
         int $result = (int)0;
         $result = this.getLobbyCountdown ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 14:  // corbaGame/wordy/isInLobbyCountdown
       {
         boolean $result = false;
         $result = this.isInLobbyCountdown ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 15:  // corbaGame/wordy/getServerTimestamp
       {
         int $result = (int)0;
         $result = this.getServerTimestamp ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 16:  // corbaGame/wordy/isGameActive
       {
         boolean $result = false;
         $result = this.isGameActive ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 17:  // corbaGame/wordy/getGameEnded
       {
         boolean $result = false;
         $result = this.getGameEnded ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 18:  // corbaGame/wordy/getWinnerName
       {
         String $result = null;
         $result = this.getWinnerName ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  // Enhanced game management
       case 19:  // corbaGame/wordy/startNewRound
       {
         this.startNewRound ();
         out = $rh.createReply();
         break;
       }

       case 20:  // corbaGame/wordy/lobbyPlayerCount
       {
         double $result = (double)0;
         $result = this.lobbyPlayerCount ();
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 21:  // corbaGame/wordy/leaveGame
       {
         try {
           String playerName = in.read_string ();
           this.leaveGame (playerName);
           out = $rh.createReply();
         } catch (corbaGame.GameException $ex) {
           out = $rh.createExceptionReply ();
           corbaGame.GameExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 22:  // corbaGame/wordy/displayWordList
       {
         String $result[] = null;
         $result = this.displayWordList ();
         out = $rh.createReply();
         corbaGame.getTopHelper.write (out, $result);
         break;
       }

       case 23:  // corbaGame/wordy/displayWinsList
       {
         String $result[] = null;
         $result = this.displayWinsList ();
         out = $rh.createReply();
         corbaGame.getWinsHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corbaGame/wordy:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public wordy _this() 
  {
    return wordyHelper.narrow(
    super._this_object());
  }

  public wordy _this(org.omg.CORBA.ORB orb) 
  {
    return wordyHelper.narrow(
    super._this_object(orb));
  }


} // class wordyPOA
