package corbaGame;


/**
* corbaGame/wordy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Thursday, 17 July 2025 1:31:25 PM SGT
*/

public interface wordy extends wordyOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface wordy
