package corbaGame;

/**
* corbaGame/wordyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Thursday, 17 July 2025 1:31:25 PM SGT
*/

public final class wordyHolder implements org.omg.CORBA.portable.Streamable
{
  public corbaGame.wordy value = null;

  public wordyHolder ()
  {
  }

  public wordyHolder (corbaGame.wordy initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbaGame.wordyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbaGame.wordyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbaGame.wordyHelper.type ();
  }

}
