package corbaGame;


/**
* corbaGame/wordyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Thursday, 17 July 2025 1:31:25 PM SGT
*/

public interface wordyOperations 
{
  void login (String username, String password) throws corbaGame.checkLogin, corbaGame.notFound, corbaGame.invalid, corbaGame.validatedLogin;
  void exit (String username);
  boolean joinLobby (String playerName) throws corbaGame.GameException;
  void timerServer ();
  double gettimer ();
  String getGeneratedLetter ();
  String playerInGameList ();
  void playWord (String playerName, String word) throws corbaGame.InvalidWord;
  String getValidWordFromClients ();
  void getWinner () throws corbaGame.isSameLength, corbaGame.getWin, corbaGame.getRoundWin;
  void generateLetters ();

  // Play again voting methods
  void votePlayAgain (String playerName);
  String[] getPlayAgainList ();

  // New synchronized timer methods
  String getGameState ();
  int getCurrentGameTime ();
  int getLobbyCountdown ();
  boolean isInLobbyCountdown ();
  int getServerTimestamp ();
  boolean isGameActive ();
  boolean getGameEnded ();
  String getWinnerName ();

  // Enhanced game management
  void startNewRound ();
  double lobbyPlayerCount ();
  void leaveGame (String playerName) throws corbaGame.GameException;
  String[] displayWordList ();
  String[] displayWinsList ();
} // interface wordyOperations
