package corbaGame;


/**
* corbaGame/wordyHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Thursday, 17 July 2025 1:31:25 PM SGT
*/

abstract public class wordyHelper
{
  private static String  _id = "IDL:corbaGame/wordy:1.0";

  public static void insert (org.omg.CORBA.Any a, corbaGame.wordy that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static corbaGame.wordy extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (corbaGame.wordyHelper.id (), "wordy");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static corbaGame.wordy read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_wordyStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, corbaGame.wordy value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static corbaGame.wordy narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof corbaGame.wordy)
      return (corbaGame.wordy)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      corbaGame._wordyStub stub = new corbaGame._wordyStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static corbaGame.wordy unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof corbaGame.wordy)
      return (corbaGame.wordy)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      corbaGame._wordyStub stub = new corbaGame._wordyStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
