package Server_Java.corbaGame;

/**
* corbaGame/GameExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Friday, 26 May 2023 11:05:13 PM SGT
*/

public final class GameExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public GameException value = null;

  public GameExceptionHolder ()
  {
  }

  public GameExceptionHolder (GameException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameExceptionHelper.type ();
  }

}
