package Server_Java.corbaGame;


/**
* corbaGame/getRoundWin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Friday, 26 May 2023 11:05:13 PM SGT
*/

public final class getRoundWin extends org.omg.CORBA.UserException
{
  public String message = null;

  public getRoundWin ()
  {
    super(getRoundWinHelper.id());
  } // ctor

  public getRoundWin (String _message)
  {
    super(getRoundWinHelper.id());
    message = _message;
  } // ctor


  public getRoundWin (String $reason, String _message)
  {
    super(getRoundWinHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class getRoundWin
