package Server_Java.corbaGame;


/**
* corbaGame/invalid.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Friday, 26 May 2023 11:05:13 PM SGT
*/

public final class invalid extends org.omg.CORBA.UserException
{
  public String message = null;

  public invalid ()
  {
    super(invalidHelper.id());
  } // ctor

  public invalid (String _message)
  {
    super(invalidHelper.id());
    message = _message;
  } // ctor


  public invalid (String $reason, String _message)
  {
    super(invalidHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class invalid
