package Server_Java.corbaGame;

/**
* corbaGame/notEnoughPlayersHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Thursday, 25 May 2023 1:47:03 PM SGT
*/

public final class notEnoughPlayersHolder implements org.omg.CORBA.portable.Streamable
{
  public notEnoughPlayers value = null;

  public notEnoughPlayersHolder ()
  {
  }

  public notEnoughPlayersHolder (notEnoughPlayers initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = notEnoughPlayersHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    notEnoughPlayersHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return notEnoughPlayersHelper.type ();
  }

}
