package Server_Java.corbaGame;

/**
* corbaGame/notFoundHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Thursday, 25 May 2023 1:47:03 PM SGT
*/

public final class notFoundHolder implements org.omg.CORBA.portable.Streamable
{
  public notFound value = null;

  public notFoundHolder ()
  {
  }

  public notFoundHolder (notFound initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = notFoundHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    notFoundHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return notFoundHelper.type ();
  }

}
