package Server_Java.corbaGame;

/**
* corbaGame/validatedLoginHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Friday, 26 May 2023 10:13:22 AM SGT
*/

public final class validatedLoginHolder implements org.omg.CORBA.portable.Streamable
{
  public validatedLogin value = null;

  public validatedLoginHolder ()
  {
  }

  public validatedLoginHolder (validatedLogin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = validatedLoginHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    validatedLoginHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return validatedLoginHelper.type ();
  }

}
