package Server_Java.corbaGame;


/**
* corbaGame/wordyPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Friday, 26 May 2023 10:13:22 AM SGT
*/

public abstract class wordyPOA extends org.omg.PortableServer.Servant
 implements wordyOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("login", new java.lang.Integer (0));
    _methods.put ("exit", new java.lang.Integer (1));
    _methods.put ("joinLobby", new java.lang.Integer (2));
    _methods.put ("timerServer", new java.lang.Integer (3));
    _methods.put ("gettimer", new java.lang.Integer (4));
    _methods.put ("getGeneratedLetter", new java.lang.Integer (5));
    _methods.put ("playerInGameList", new java.lang.Integer (6));
    _methods.put ("playWord", new java.lang.Integer (7));
    _methods.put ("getValidWordFromClients", new java.lang.Integer (8));
    _methods.put ("getWinner", new java.lang.Integer (9));
    _methods.put ("generateLetters", new java.lang.Integer (10));
    _methods.put ("startNewRound", new java.lang.Integer (11));
    _methods.put ("status", new java.lang.Integer (12));
    _methods.put ("lobbyPlayerCount", new java.lang.Integer (13));
    _methods.put ("leaveGame", new java.lang.Integer (14));
    _methods.put ("displayWordList", new java.lang.Integer (15));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // corbaGame/wordy/login
       {
         try {
           String username = in.read_string ();
           String password = in.read_string ();
           this.login (username, password);
           out = $rh.createReply();
         } catch (checkLogin $ex) {
           out = $rh.createExceptionReply ();
           checkLoginHelper.write (out, $ex);
         } catch (notFound $ex) {
           out = $rh.createExceptionReply ();
           notFoundHelper.write (out, $ex);
         } catch (invalid $ex) {
           out = $rh.createExceptionReply ();
           invalidHelper.write (out, $ex);
         } catch (validatedLogin $ex) {
           out = $rh.createExceptionReply ();
           validatedLoginHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // corbaGame/wordy/exit
       {
         String username = in.read_string ();
         this.exit (username);
         out = $rh.createReply();
         break;
       }

       case 2:  // corbaGame/wordy/joinLobby
       {
         try {
           String playerName = in.read_string ();
           boolean $result = false;
           $result = this.joinLobby (playerName);
           out = $rh.createReply();
           out.write_boolean ($result);
         } catch (GameException $ex) {
           out = $rh.createExceptionReply ();
           GameExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // corbaGame/wordy/timerServer
       {
         this.timerServer ();
         out = $rh.createReply();
         break;
       }

       case 4:  // corbaGame/wordy/gettimer
       {
         double $result = (double)0;
         $result = this.gettimer ();
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 5:  // corbaGame/wordy/getGeneratedLetter
       {
         String $result = null;
         $result = this.getGeneratedLetter ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // corbaGame/wordy/playerInGameList
       {
         String $result = null;
         $result = this.playerInGameList ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // corbaGame/wordy/playWord
       {
         try {
           String playerName = in.read_string ();
           String word = in.read_string ();
           this.playWord (playerName, word);
           out = $rh.createReply();
         } catch (InvalidWord $ex) {
           out = $rh.createExceptionReply ();
           InvalidWordHelper.write (out, $ex);
         }
         break;
       }

       case 8:  // corbaGame/wordy/getValidWordFromClients
       {
         String $result = null;
         $result = this.getValidWordFromClients ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 9:  // corbaGame/wordy/getWinner
       {
         try {
           this.getWinner ();
           out = $rh.createReply();
         } catch (isSameLength $ex) {
           out = $rh.createExceptionReply ();
           isSameLengthHelper.write (out, $ex);
         } catch (getWin $ex) {
           out = $rh.createExceptionReply ();
           getWinHelper.write (out, $ex);
         } catch (getRoundWin $ex) {
           out = $rh.createExceptionReply ();
           getRoundWinHelper.write (out, $ex);
         }
         break;
       }

       case 10:  // corbaGame/wordy/generateLetters
       {
         this.generateLetters ();
         out = $rh.createReply();
         break;
       }

       case 11:  // corbaGame/wordy/startNewRound
       {
         this.startNewRound ();
         out = $rh.createReply();
         break;
       }

       case 12:  // corbaGame/wordy/status
       {
         String playerName = in.read_string ();
         boolean $result = false;
         $result = this.status (playerName);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 13:  // corbaGame/wordy/lobbyPlayerCount
       {
         double $result = (double)0;
         $result = this.lobbyPlayerCount ();
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 14:  // corbaGame/wordy/leaveGame
       {
         try {
           String playerName = in.read_string ();
           this.leaveGame (playerName);
           out = $rh.createReply();
         } catch (GameException $ex) {
           out = $rh.createExceptionReply ();
           GameExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 15:  // corbaGame/wordy/displayWordList
       {
         String $result[] = null;
         $result = this.displayWordList ();
         out = $rh.createReply();
         getTopHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corbaGame/wordy:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public wordy _this() 
  {
    return wordyHelper.narrow(
    super._this_object());
  }

  public wordy _this(org.omg.CORBA.ORB orb) 
  {
    return wordyHelper.narrow(
    super._this_object(orb));
  }


} // class wordyPOA
