package Server_Java.corbaGame;


/**
* corbaGame/wordyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Friday, 26 May 2023 11:05:13 PM SGT
*/

public interface wordyOperations 
{
  void login (String username, String password) throws checkLogin, notFound, invalid, validatedLogin;
  void exit (String username);
  boolean joinLobby (String playerName) throws GameException;
  void timerServer ();
  double gettimer ();
  String getGeneratedLetter ();
  String playerInGameList ();
  void playWord (String playerName, String word) throws InvalidWord;
  String getValidWordFromClients ();
  void getWinner () throws isSameLength, getWin, getRoundWin;
  void generateLetters ();
  void startNewRound ();
  boolean status (String playerName);
  double lobbyPlayerCount ();
  void leaveGame (String playerName) throws GameException;
  String[] displayWordList ();
  String[] displayWinsList ();
  // Play again voting methods
  void votePlayAgain (String playerName);
  String[] getPlayAgainList ();
  // New synchronized timer methods
  String getGameState ();
} // interface wordyOperations
