package Server_Java.corbaGame;


/**
* corbaGame/wordy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaGame.idl
* Thursday, 25 May 2023 1:47:03 PM SGT
*/

public interface wordy extends wordyOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface wordy
