package Client_Java.corba;


/**
* corba/checkLogin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Wednesday, 24 May 2023 9:37:42 AM SGT
*/

public final class checkLogin extends org.omg.CORBA.UserException
{
  public String message = null;

  public checkLogin ()
  {
    super(checkLoginHelper.id());
  } // ctor

  public checkLogin (String _message)
  {
    super(checkLoginHelper.id());
    message = _message;
  } // ctor


  public checkLogin (String $reason, String _message)
  {
    super(checkLoginHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class checkLogin
