package Client_Java.corba;

/**
* corba/getRoundWinHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Wednesday, 24 May 2023 9:37:42 AM SGT
*/

public final class getRoundWinHolder implements org.omg.CORBA.portable.Streamable
{
  public getRoundWin value = null;

  public getRoundWinHolder ()
  {
  }

  public getRoundWinHolder (getRoundWin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = getRoundWinHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    getRoundWinHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return getRoundWinHelper.type ();
  }

}
