package Client_Java.corba;

/**
* corba/getWinHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Wednesday, 24 May 2023 9:37:42 AM SGT
*/

public final class getWinHolder implements org.omg.CORBA.portable.Streamable
{
  public getWin value = null;

  public getWinHolder ()
  {
  }

  public getWinHolder (getWin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = getWinHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    getWinHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return getWinHelper.type ();
  }

}
