package Client_Java.corba;

/**
* corba/isSameLengthHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Wednesday, 24 May 2023 9:37:42 AM SGT
*/

public final class isSameLengthHolder implements org.omg.CORBA.portable.Streamable
{
  public isSameLength value = null;

  public isSameLengthHolder ()
  {
  }

  public isSameLengthHolder (isSameLength initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = isSameLengthHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    isSameLengthHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return isSameLengthHelper.type ();
  }

}
