package Client_Java.corba;


/**
* corba/lobby.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Monday, May 15, 2023 8:32:15 AM CST
*/

public interface lobby extends lobbyOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface lobby
