package Client_Java.corba;


/**
* corba/lobbyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Monday, May 15, 2023 8:32:15 AM CST
*/

public interface lobbyOperations 
{
  void time (double countdown);
  void playerList (String message);
} // interface lobbyOperations
