package Client_Java.corba;


/**
* corba/sendLobbyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Monday, May 15, 2023 8:32:15 AM CST
*/

public interface sendLobbyOperations 
{
  String sendTimer (lobby objref, String message);
  String sendPlayerList (lobby objref, String message);
} // interface sendLobbyOperations
