package Client_Java.corba;


/**
* corba/sendLobbyHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Monday, May 15, 2023 8:32:15 AM CST
*/

abstract public class sendLobbyHelper
{
  private static String  _id = "IDL:corba/sendLobby:1.0";

  public static void insert (org.omg.CORBA.Any a, sendLobby that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static sendLobby extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (sendLobbyHelper.id (), "sendLobby");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static sendLobby read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_sendLobbyStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, sendLobby value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static sendLobby narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof sendLobby)
      return (sendLobby)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _sendLobbyStub stub = new _sendLobbyStub();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static sendLobby unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof sendLobby)
      return (sendLobby)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _sendLobbyStub stub = new _sendLobbyStub();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
