package Client_Java.corba;

/**
* corba/sendLobbyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Monday, May 15, 2023 8:32:15 AM CST
*/

public final class sendLobbyHolder implements org.omg.CORBA.portable.Streamable
{
  public sendLobby value = null;

  public sendLobbyHolder ()
  {
  }

  public sendLobbyHolder (sendLobby initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sendLobbyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sendLobbyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sendLobbyHelper.type ();
  }

}
