package Client_Java.corba;

/**
* corba/validatedLoginHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Wednesday, 24 May 2023 9:37:42 AM SGT
*/

public final class validatedLoginHolder implements org.omg.CORBA.portable.Streamable
{
  public validatedLogin value = null;

  public validatedLoginHolder ()
  {
  }

  public validatedLoginHolder (validatedLogin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = validatedLoginHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    validatedLoginHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return validatedLoginHelper.type ();
  }

}
