package Client_Java.corba;

/**
* corba/WordyCallbackHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Wednesday, 24 May 2023 9:37:42 AM SGT
*/

public final class WordyCallbackHolder implements org.omg.CORBA.portable.Streamable
{
  public WordyCallback value = null;

  public WordyCallbackHolder ()
  {
  }

  public WordyCallbackHolder (WordyCallback initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordyCallbackHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordyCallbackHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordyCallbackHelper.type ();
  }

}
