package Client_Java.corba;


/**
* corba/WordyCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Tuesday, 23 May 2023 12:31:25 AM SGT
*/

public interface WordyCallbackOperations 
{
  void sendGeneratedLetter (String letters);
} // interface WordyCallbackOperations
