package Client_Java.corba;


/**
* corba/WordyCallback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Tuesday, 23 May 2023 12:12:10 AM SGT
*/

public interface WordyCallback extends WordyCallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface WordyCallback
