package Client_Java.corba;


/**
* corba/wordyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Monday, May 15, 2023 8:32:15 AM CST
*/

public interface wordyOperations 
{
  String login (String username, String password);
  void exit (String username);
  boolean joinGame (String playerName) throws GameException;
  void playWord (String playerName, String word) throws GameException;
  boolean status (String playerName);
  String generateLetters ();
  double timer ();
  void leaveGame (String playerName) throws GameException;
} // interface wordyOperations
