package Client_Java.corba;


/**
* corba/WordyCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Monday, 22 May 2023 9:47:57 PM SGT
*/

public interface WordyCallbackOperations 
{
  void sendGeneratedLetter (String letters);
} // interface WordyCallbackOperations
