package Client_Java.corba;


/**
* corba/WordyCallback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Sunday, 14 May 2023 9:41:17 PM SGT
*/

public interface WordyCallback extends WordyCallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface WordyCallback
