package Client_Java.corba;


/**
* corba/WordyCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Wednesday, 24 May 2023 9:37:42 AM SGT
*/

public interface WordyCallbackOperations 
{
  void sendGeneratedLetter (String letters);
} // interface WordyCallbackOperations
