package Client_Java.corba;

/**
* corba/wordyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Tuesday, 23 May 2023 12:31:25 AM SGT
*/

public final class wordyHolder implements org.omg.CORBA.portable.Streamable
{
  public wordy value = null;

  public wordyHolder ()
  {
  }

  public wordyHolder (wordy initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyHelper.type ();
  }

}
