package Client_Java.corba;


/**
* corba/wordyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Monday, 22 May 2023 9:47:57 PM SGT
*/

public interface wordyOperations 
{
  String login (String username, String password);
  void exit (String username);
  boolean joinLobby (String playerName) throws GameException;
  void timerServer ();
  double gettimer ();
  String getGeneratedLetter ();
  String playerInGameList ();
  void playWord (String playerName, String word) throws InvalidWord;
  String getValidWordFromClients ();
  void generateLetters ();
  boolean status (String playerName);
  double lobbyPlayerCount ();
  void leaveGame (String playerName) throws GameException;
} // interface wordyOperations
