package src.Client_Java.corba;


import Client_Java.corba.GameExceptionHelper;

/**
* corba/GameException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Tuesday, 23 May 2023 11:35:30 PM SGT
*/

public final class GameException extends org.omg.CORBA.UserException
{
  public String message = null;

  public GameException ()
  {
    super(Client_Java.corba.GameExceptionHelper.id());
  } // ctor

  public GameException (String _message)
  {
    super(Client_Java.corba.GameExceptionHelper.id());
    message = _message;
  } // ctor


  public GameException (String $reason, String _message)
  {
    super(GameExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class GameException
