package src.Client_Java.corba;

import Client_Java.corba.GameException;
import Client_Java.corba.GameExceptionHelper;

/**
* corba/GameExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Tuesday, 23 May 2023 11:35:30 PM SGT
*/

public final class GameExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public Client_Java.corba.GameException value = null;

  public GameExceptionHolder ()
  {
  }

  public GameExceptionHolder (GameException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Client_Java.corba.GameExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Client_Java.corba.GameExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameExceptionHelper.type ();
  }

}
