package src.Client_Java.corba;

import Client_Java.corba.InvalidWord;
import Client_Java.corba.InvalidWordHelper;

/**
* corba/InvalidWordHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Tuesday, 23 May 2023 11:35:30 PM SGT
*/

public final class InvalidWordHolder implements org.omg.CORBA.portable.Streamable
{
  public Client_Java.corba.InvalidWord value = null;

  public InvalidWordHolder ()
  {
  }

  public InvalidWordHolder (InvalidWord initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Client_Java.corba.InvalidWordHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Client_Java.corba.InvalidWordHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return InvalidWordHelper.type ();
  }

}
