package src.Client_Java.corba;


import Client_Java.corba.GameException;
import Client_Java.corba.InvalidWord;

/**
* corba/wordyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Tuesday, 23 May 2023 11:35:30 PM SGT
*/

public interface wordyOperations 
{
  void login (String username, String password) throws checkLogin, notFound, invalid, validatedLogin;
  void exit (String username);
  boolean joinLobby (String playerName) throws Client_Java.corba.GameException;
  void timerServer ();
  double gettimer ();
  String getGeneratedLetter ();
  String playerInGameList ();
  void playWord (String playerName, String word) throws InvalidWord;
  String getValidWordFromClients ();
  String getWinner () throws isSameLength;
  void generateLetters ();
  void startNewRound ();
  boolean status (String playerName);
  double lobbyPlayerCount ();
  void leaveGame (String playerName) throws GameException;
} // interface wordyOperations
