package src.Client_Java.corba;


/**
* corba/WordyCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Tuesday, 23 May 2023 11:35:30 PM SGT
*/

public interface WordyCallbackOperations 
{
  void sendGeneratedLetter (String letters);
} // interface WordyCallbackOperations
