package Server_Java.CORBA_IDL;


/**
* CORBA_IDL/wordyPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA_IDL.idl
* Thursday, 27 April 2023 7:41:17 PM SGT
*/

public abstract class wordyPOA extends org.omg.PortableServer.Servant
 implements wordyOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("login", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CORBA_IDL/wordy/login
       {
         String username = in.read_string ();
         String password = in.read_string ();
         this.login (username, password);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CORBA_IDL/wordy:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public wordy _this() 
  {
    return wordyHelper.narrow(
    super._this_object());
  }

  public wordy _this(org.omg.CORBA.ORB orb) 
  {
    return wordyHelper.narrow(
    super._this_object(orb));
  }


} // class wordyPOA
