package Server_Java.CORBA_IDL;


/**
* CORBA_IDL/wordyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA_IDL.idl
* Friday, 28 April 2023 7:25:45 PM SGT
*/

public interface wordyOperations 
{
  String login (String username, String password);
} // interface wordyOperations
