package src.Server_Java.corba;


/**
* corba/isSameLength.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Tuesday, 23 May 2023 11:35:17 PM SGT
*/

public final class isSameLength extends org.omg.CORBA.UserException
{
  public String message = null;

  public isSameLength ()
  {
    super(isSameLengthHelper.id());
  } // ctor

  public isSameLength (String _message)
  {
    super(isSameLengthHelper.id());
    message = _message;
  } // ctor


  public isSameLength (String $reason, String _message)
  {
    super(isSameLengthHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class isSameLength
