package src.Server_Java.corba;


/**
* corba/notFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Tuesday, 23 May 2023 11:35:17 PM SGT
*/

public final class notFound extends org.omg.CORBA.UserException
{
  public String message = null;

  public notFound ()
  {
    super(notFoundHelper.id());
  } // ctor

  public notFound (String _message)
  {
    super(notFoundHelper.id());
    message = _message;
  } // ctor


  public notFound (String $reason, String _message)
  {
    super(notFoundHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class notFound
