package src.Server_Java.corba;

/**
* corba/notFoundHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Tuesday, 23 May 2023 11:35:17 PM SGT
*/

public final class notFoundHolder implements org.omg.CORBA.portable.Streamable
{
  public notFound value = null;

  public notFoundHolder ()
  {
  }

  public notFoundHolder (notFound initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = notFoundHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    notFoundHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return notFoundHelper.type ();
  }

}
