package src.Server_Java.corba;


/**
* corba/validatedLogin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Tuesday, 23 May 2023 11:35:17 PM SGT
*/

public final class validatedLogin extends org.omg.CORBA.UserException
{
  public String message = null;

  public validatedLogin ()
  {
    super(validatedLoginHelper.id());
  } // ctor

  public validatedLogin (String _message)
  {
    super(validatedLoginHelper.id());
    message = _message;
  } // ctor


  public validatedLogin (String $reason, String _message)
  {
    super(validatedLoginHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class validatedLogin
