package src.Server_Java.corba;


import Server_Java.corba.WordyCallback;
import Server_Java.corba._WordyCallbackStub;

/**
* corba/WordyCallbackHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Tuesday, 23 May 2023 11:35:17 PM SGT
*/

abstract public class WordyCallbackHelper
{
  private static String  _id = "IDL:corba/WordyCallback:1.0";

  public static void insert (org.omg.CORBA.Any a, Server_Java.corba.WordyCallback that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Server_Java.corba.WordyCallback extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (WordyCallbackHelper.id (), "WordyCallback");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Server_Java.corba.WordyCallback read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (Server_Java.corba._WordyCallbackStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Server_Java.corba.WordyCallback value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Server_Java.corba.WordyCallback narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Server_Java.corba.WordyCallback)
      return (Server_Java.corba.WordyCallback)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Server_Java.corba._WordyCallbackStub stub = new Server_Java.corba._WordyCallbackStub();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Server_Java.corba.WordyCallback unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Server_Java.corba.WordyCallback)
      return (WordyCallback)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Server_Java.corba._WordyCallbackStub stub = new _WordyCallbackStub();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
