package src.Server_Java.corba;

import Server_Java.corba.wordy;
import Server_Java.corba.wordyHelper;

/**
* corba/wordyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Tuesday, 23 May 2023 11:35:17 PM SGT
*/

public final class wordyHolder implements org.omg.CORBA.portable.Streamable
{
  public Server_Java.corba.wordy value = null;

  public wordyHolder ()
  {
  }

  public wordyHolder (wordy initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server_Java.corba.wordyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server_Java.corba.wordyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyHelper.type ();
  }

}
