package src.Server_Java.corba;


import Server_Java.corba.WordyCallbackOperations;

/**
* corba/WordyCallback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Tuesday, 23 May 2023 11:35:17 PM SGT
*/

public interface WordyCallback extends WordyCallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface WordyCallback
