module corba {
   exception GameException {
        string message;
      };
    interface wordy{
        string login(in string username , in string password );
        boolean joinGame(in string playerName) raises (GameException);
        void playWord(in string playerName, in string word) raises (GameException);
        boolean status(in string playerName);
        string generateLetters();
        boolean timer();
        void leaveGame(in string playerName) raises (GameException);
        void receiveMessage(in string receiveMessage);
    };
    typedef sequence<string> Players;
  interface WordyCallback {
        void notifyCountdownStarted(in long count );
        void notifyPlayersList(in Players players);
        void notifyGameStarted();
        void sendMessage(in string sendMessage);
  };
};
#pragma prefix "Server_Java"